apiVersion: skaffold/v1alpha4
kind: Config
build:
  tagPolicy:
    sha256: {}
  local:
    push: true
  artifacts:
  - image: pchico83/vote
    context: vote
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests/vote-deployment.yaml
